### ISSUE TITLE
[FE/Feat] 닉네임 수정, 프로젝트 생성, 정보 수정, 팀원 관리 구현

### ISSUE THREAD

**Issue by yh-project** [Shooot-PJT/shooot#16]
## 📔 Description

사용자 정보인 닉네임 관리와 프로젝트 정보 관리 로직 구현

## 🐈 Todo

- [x] 닉네임 수정 구현
- [x] 프로젝트 생성 구현
- [x] 프로젝트 정보 수정 구현
- [x] 팀원 초대, 추방 구현

**Comment by yh-project** [comment]
created branch [`feat/31-manage-info`](/s11-final/S11P31D109/-/compare/develop...feat%2F31-manage-info) to address this issue

**Comment by yh-project** [comment]
marked the checklist item **닉네임 수정 구현** as completed

**Comment by yh-project** [comment]
mentioned in commit 6e9e6ec6600bba6bfa389a26b22d9c28e5f0ce65

**Comment by yh-project** [comment]
mentioned in commit 10d3e5422df15ffbccc4fec6579f482a58ce7562

**Comment by yh-project** [comment]
marked the checklist item **프로젝트 생성 구현** as completed

**Comment by yh-project** [comment]
mentioned in commit c5639c83fa5620f0ad0be61d0201365a9877e85d

**Comment by yh-project** [comment]
프로젝트 수정 - patch 로 바뀐건지 확인

**Comment by yh-project** [comment]
mentioned in commit 965eae7ad28c62a932a2ac2c66356080be4f500c

**Comment by yh-project** [comment]
회원 검색 확인 필요 - 명세서에만 없는건지 개발이 안된건지

**Comment by yh-project** [comment]
프로젝트 팀원 초대 - body에 userId를 담아야하는데 userId를 주는 곳이 없음

**Comment by yh-project** [comment]
mentioned in commit 3387708cb69a15a4ea972e6b846c2d36e311fb2e

**Comment by yh-project** [comment]
mentioned in commit 73fe341a0bca8783c0373e8b2d2ece7829536c65

**Comment by yh-project** [comment]
mentioned in commit 909c3373e6f188c575123474fe33a2a74128334d

**Comment by yh-project** [comment]
mentioned in commit 9bd3091f78d9f0601d61865df2120767fb23888d

**Comment by yh-project** [comment]
marked the checklist item **프로젝트 정보 수정 구현** as completed

**Comment by yh-project** [comment]
marked the checklist item **팀원 초대, 추방 구현** as completed

**Comment by yh-project** [comment]
mentioned in commit d505691f8d1693b606a274fb379b794024c7d540

**Comment by yh-project** [comment]
mentioned in commit fbe5ac93ade75d7d30c6e401906dde21677a4f6e

**Comment by yh-project** [comment]
mentioned in commit 5a282222058a88f7215ba05f69c77d1fc812146b

**Comment by yh-project** [comment]
mentioned in commit fcd809d2c363d420eb2b54aa9fdbcd2c25962e46
