### ISSUE TITLE
[FE/BE/Feat] mocking 을 위한 브라우저 service worker 구현

### ISSUE THREAD

**Issue by yh-project** [Shooot-PJT/shooot#19]
## 📔 Description

사용자들이 우리가 제공하는 웹사이트에서 이용하지 않고 각자의 개발 환경에서 사용할 경우 환경을 제어할 수 없음.
따라서, 직접 service worker 를 통한 mocking 을 구현하여 사용자 각자의 개발 환경에서 사용할 수 있도록 하기 위함.
그리고 이 service worker 가 동작하는 환경을 라이브러리화 하여 npm 에 배포하고자 함.

## 🐈 Todo

- [x] service worker 기본 설정
- [x] service worker 의 on/off 설정이 가능하도록 구현
- [x] 라이브러리에서 필요한 config 설정
- [x] service worker 가 request 를 가로채는 과정 구현

**Comment by yh-project** [comment]
created branch [`feat/36-mocking-service-worker`](/s11-final/S11P31D109/-/compare/develop...feat%2F36-mocking-service-worker) to address this issue

**Comment by yh-project** [comment]
mentioned in commit 71c30f45aede3db5d8ecd5785aeccc09d995b30d

**Comment by yh-project** [comment]
mentioned in commit 7282e41c748d45edeea8220bb71612f5727008d6

**Comment by yh-project** [comment]
mentioned in commit 6124289f4d5e980c58599ef521ab4d69260b124a

**Comment by yh-project** [comment]
mentioned in commit 5d2ff0a0fe97baf9666117269d16fa889edec493

**Comment by yh-project** [comment]
marked the checklist item **service worker 기본 설정** as completed

**Comment by yh-project** [comment]
marked the checklist item **service worker 의 on/off 설정이 가능하도록 구현** as completed

**Comment by yh-project** [comment]
marked the checklist item **라이브러리에서 필요한 config 설정** as completed

**Comment by yh-project** [comment]
marked the checklist item **service worker 가 request 를 가로채는 과정 구현** as completed
