### ISSUE TITLE
[BE/Feat] 문서 - API 기능 구현

### ISSUE THREAD

**Issue by yh-project** [Shooot-PJT/shooot#20]
In GitLab by @jangcheolhyeon on Oct 28, 2024, 14:50

## 📔 Description

API 문서(API) 기능 구현

## 🐈 Todo

- [x] API 등록
- [x] API 리스트 조회
- [x] API 상세 조회
- [x] API 수정
- [x] API Toggle(secure, real server) 변경
- [x] API 삭제

**Comment by yh-project** [comment]
In GitLab by @jangcheolhyeon on Oct 28, 2024, 14:51

created branch [`feat/20-docs-api`](/s11-final/S11P31D109/-/compare/develop...feat%2F20-docs-api) to address this issue

**Comment by yh-project** [comment]
In GitLab by @jangcheolhyeon on Oct 28, 2024, 17:42

mentioned in commit e9de972bf474f4a1ea85c90a7f09e2026321191e

**Comment by yh-project** [comment]
In GitLab by @jangcheolhyeon on Oct 28, 2024, 18:35

marked the checklist item **API 등록** as completed

**Comment by yh-project** [comment]
In GitLab by @jangcheolhyeon on Oct 28, 2024, 18:35

marked the checklist item **API 리스트 조회** as completed

**Comment by yh-project** [comment]
In GitLab by @jangcheolhyeon on Oct 28, 2024, 18:35

marked the checklist item **API 상세 조회** as completed

**Comment by yh-project** [comment]
In GitLab by @jangcheolhyeon on Oct 28, 2024, 18:35

marked the checklist item **API 수정** as completed

**Comment by yh-project** [comment]
In GitLab by @jangcheolhyeon on Oct 28, 2024, 18:35

marked the checklist item **API Toggle(secure, real server) 변경** as completed

**Comment by yh-project** [comment]
In GitLab by @jangcheolhyeon on Oct 28, 2024, 18:35

marked the checklist item **API 삭제** as completed
