### ISSUE TITLE
[FE/Feat] 사용자 도메인, 프로젝트 도메인 예외처리

### ISSUE THREAD

**Issue by yh-project** [Shooot-PJT/shooot#26]
## 📔 Description

사용자, 프로젝트 도메인에서 예외처리, validation 등의 추가 작업 수행
발견할 때마다 todo 1개씩 추가하면서 작업

## 🐈 Todo

- [x] 닉네임 정규식 수정 (16자)
- [x] 로그아웃 후 navigation 수정
- [x] 프로젝트 영문명 수정 불가 경고문 수정
- [x] 프로젝트 생성 & 수정 경고문 수정
- [x] 프로젝트 정보 변경 시 slider 수정
- [x] 팀원 초대 로직 추가 (본인 추가 불가, 기존 팀원 추가 불가)
- [x] 팀원 추방 팝업 & 모달 제어 로직 추가 (취소 시에는 팝업만, 추방 시에는 모달까지)
- [x] react-slick 뷰 깨지는 문제 수정
- [x] 쿼리 refetch -> useQuery 재선언 방식에서 캐싱 데이터 직접 접근하여 refetch 하는 방식으로 수정

**Comment by yh-project** [comment]
created branch [`feat/50-exception-validation`](/s11-final/S11P31D109/-/compare/develop...feat%2F50-exception-validation) to address this issue

**Comment by yh-project** [comment]
mentioned in commit de35df8c2bcf21544b1b4c2f1dc02f73fb10049a

**Comment by yh-project** [comment]
mentioned in commit 203c79e34756d9b6c55760714b9b635c8a9fc831

**Comment by yh-project** [comment]
mentioned in commit 61d7fdda2cb635266a215b595be4da7a77d7a7fa

**Comment by yh-project** [comment]
mentioned in commit bc9fd3a7cabd90fb27c208a683757b458b3dbe82

**Comment by yh-project** [comment]
mentioned in commit 7bdfef6f19b4ffe10100ed8eb0e8008cef5d5ea0

**Comment by yh-project** [comment]
mentioned in commit 7adbfd0e1878949a7ce1e5bd493e1028b5642dfa

**Comment by yh-project** [comment]
mentioned in commit 21b1ac8e2f3b9a78d01ea5eca616074666d36d05

**Comment by yh-project** [comment]
mentioned in commit 5e4b5abbc44c1edbc63446a716b9c55aaf7ae45a

**Comment by yh-project** [comment]
mentioned in commit 16cef99d38298ed351f1f9554129c87350d35e03

**Comment by yh-project** [comment]
mentioned in commit 08badb9aaa1bb9e7104232c214a07299c4883c5a

**Comment by yh-project** [comment]
mentioned in commit d30fc2b8068536def06c419407a750c9991bf720

**Comment by yh-project** [comment]
marked the checklist item **닉네임 정규식 수정 (16자)** as completed

**Comment by yh-project** [comment]
marked the checklist item **로그아웃 후 navigation 수정** as completed

**Comment by yh-project** [comment]
marked the checklist item **프로젝트 영문명 수정 불가 경고문 수정** as completed

**Comment by yh-project** [comment]
marked the checklist item **프로젝트 생성 & 수정 경고문 수정** as completed

**Comment by yh-project** [comment]
marked the checklist item **프로젝트 정보 변경 시 slider 수정** as completed

**Comment by yh-project** [comment]
marked the checklist item **팀원 초대 로직 추가 (본인 추가 불가, 기존 팀원 추가 불가)** as completed

**Comment by yh-project** [comment]
marked the checklist item **react-slick 뷰 깨지는 문제 수정** as completed

**Comment by yh-project** [comment]
marked the checklist item **팀원 추방 팝업 & 모달 제어 로직 추가 (취소 시에는 팝업만, 추방 시에는 모달까지)** as completed

**Comment by yh-project** [comment]
marked the checklist item **쿼리 refetch -> useQuery 재선언 방식에서 캐싱 데이터 직접 접근하여 refetch 하는 방식으로 수정** as completed

**Comment by yh-project** [comment]
mentioned in commit c89df0b21c0b472303760875e9301c774af4dcae
