### ISSUE TITLE
[BE/Feat] 사용자 도메인 기능 추가

### ISSUE THREAD

**Issue by yh-project** [Shooot-PJT/shooot#4]
In GitLab by @khj745700 on Oct 17, 2024, 15:49

## 📔 Description

사용자 도메인 기능 추가

## 🐈 Todo

- [x] 스프링 시큐리티 기능 병합
- [x] 사용자 도메인 기능 추가
- [x] 비동기 이벤트 사용 추상화
- [x] 세션 사용 추상화
- [x] 커스텀 에러 코드 사용 추상화

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Oct 17, 2024, 15:49

marked the checklist item **스프링 시큐리티 기능 병합** as completed

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Oct 17, 2024, 15:49

marked the checklist item **사용자 도메인 기능 추가** as completed

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Oct 17, 2024, 15:49

marked the checklist item **비동기 이벤트 사용 추상화** as completed

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Oct 17, 2024, 15:49

marked the checklist item **세션 사용 추상화** as completed

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Oct 17, 2024, 15:50

marked the checklist item **커스텀 에러 코드 사용 추상화** as completed

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Oct 17, 2024, 15:53

created branch [`feat/4-user`](/s11-final/S11P31D109/-/compare/develop...feat%2F4-user) to address this issue

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Oct 17, 2024, 15:56

mentioned in commit 1999ecf306794216ea8565d87fc165902b8e74c2

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Oct 17, 2024, 15:59

mentioned in commit c6e89c45890017d443c89d1fc9cefdc50d6af267
