### ISSUE TITLE
[Mock/Feat] 사용자의 요청 관리

### ISSUE THREAD

**Issue by yh-project** [Shooot-PJT/shooot#40]
## 📔 Description

사용자가 보낸 request 를 service worker 가 가로채서 request 의 정보들을 확인하고 이를 mocking 서버(express)로 전송하여 확인할 수 있는 과정 구현

## 🐈 Todo

- [x] request 정보 조회 구현
- [x] express 로 정보 전달 구현
- [x] express 에서 정보 조회, 응답 구현

**Comment by yh-project** [comment]
created branch [`feat/40-request-mocking`](/s11-final/S11P31D109/-/compare/develop...feat%2F40-request-mocking) to address this issue

**Comment by yh-project** [comment]
mentioned in commit e6e7b3a16bee75f948f5407a8d3ef8f5ef622ea2

**Comment by yh-project** [comment]
mentioned in commit 95d2ebd257a7f9f33e5a7952bafcf97bd52c835c

**Comment by yh-project** [comment]
mentioned in commit 24d32ba18e4118a5aeb1165198718d5da262bcaa

**Comment by yh-project** [comment]
mentioned in commit 8ef0278f530b8163b6d88122b2078c6802aa47df

**Comment by yh-project** [comment]
mentioned in commit a52e30e2a7d75c479490ac4784b0219fa5786335

**Comment by yh-project** [comment]
mentioned in commit 1ea2b00cce70adf4b5fee5333acde008977abba2

**Comment by yh-project** [comment]
mentioned in commit d6005fef249d053bb6f79044ded4218dc1eed8da

**Comment by yh-project** [comment]
mentioned in commit 07c4521309ab78145fdf52a0725e26da6211008e

**Comment by yh-project** [comment]
mentioned in commit 77b9dc46c301103b8373e4988bbe5009640425ef

**Comment by yh-project** [comment]
mentioned in commit a6d132b7d9668079a20e95347aac6c01146758eb

**Comment by yh-project** [comment]
mentioned in commit 5181bf76b3d6902301740a08b874919094d3955b

**Comment by yh-project** [comment]
marked the checklist item **request 정보 조회 구현** as completed

**Comment by yh-project** [comment]
marked the checklist item **express 로 정보 전달 구현** as completed

**Comment by yh-project** [comment]
marked the checklist item **express 에서 정보 조회, 응답 구현** as completed

**Comment by yh-project** [comment]
mentioned in commit 4ef62c9bfde2b492480cbc1ee53d1f7e5c9cf204
