### ISSUE TITLE
[FE/Feat] 프로젝트 파일 CRUD API 연결

### ISSUE THREAD

**Issue by yh-project** [Shooot-PJT/shooot#43]
In GitLab by @altys31 on Nov 6, 2024, 10:05

## 📔 Description

프로젝트 파일 CRUD API 연결

## 🐈 Todo

-   [x] 프로젝트 파일 리스트 조회
-   [x] 프로젝트 파일 추가
-   [ ] 프로젝트 파일 삭제

**Comment by yh-project** [comment]
In GitLab by @altys31 on Nov 6, 2024, 10:07

created branch [`feat/43-projectFile-api`](/s11-final/S11P31D109/-/compare/develop...feat%2F43-projectFile-api) to address this issue

**Comment by yh-project** [comment]
In GitLab by @altys31 on Nov 7, 2024, 21:34

marked the checklist item **프로젝트 파일 리스트 조회** as completed

**Comment by yh-project** [comment]
In GitLab by @altys31 on Nov 7, 2024, 21:34

marked the checklist item **프로젝트 파일 추가** as completed

**Comment by yh-project** [comment]
In GitLab by @altys31 on Nov 7, 2024, 23:40

mentioned in commit d532711b17130848d795ba986085c001c5496ffa
