### ISSUE TITLE
[FE/Fix] 사용자, 프로젝트 도메인 예외 처리, 쿼리 최적화

### ISSUE THREAD

**Issue by yh-project** [Shooot-PJT/shooot#46]
## 📔 Description

사용자, 프로젝트 도메인에서의 추가적인 예외 처리와 쿼리 최적화가 필요
예외 처리의 경우 추가될 때마다 todo 에 추가

## 🐈 Todo

- [x] 사용자, 프로젝트 도메인 쿼리 최적화
- [x] 닉네임 validation 경고 메시지 추가
- [x] 닉네임 변경 타이틀 수정
- [x] 팀장한테만 팀 정보 수정 정보들 노출
- [x] 사람 검색은 이메일로 해야함을 표시
- [x] carousel 프로젝트 로고 이미지 뷰 해결
- [x] 회원가입 step 에 따라 버튼이 안보이던 버그 해결
- [x] 프로젝트 로고 이미지 사진 혹은 .gif 만 가능하도록 경고

**Comment by yh-project** [comment]
created branch [`fix/59-query-exception`](/s11-final/S11P31D109/-/compare/develop...fix%2F59-query-exception) to address this issue

**Comment by yh-project** [comment]
mentioned in commit a3548957bc531f4e3e4a1772f1b989588fed9b8f

**Comment by yh-project** [comment]
mentioned in commit 9d21ee25df1c432286e8714a769218b3e3bd4ef6

**Comment by yh-project** [comment]
mentioned in commit 75fd091ed9efb91d1e29eb1562dd5db54c2d9562

**Comment by yh-project** [comment]
mentioned in commit 19dffca0e17146452b2b4c3a3630c530d44b4077

**Comment by yh-project** [comment]
mentioned in commit 718e1ae549ebb4263273f733594bfd330578c73b

**Comment by yh-project** [comment]
marked the checklist item **사용자, 프로젝트 도메인 쿼리 최적화** as completed

**Comment by yh-project** [comment]
mentioned in commit 542cc6aba73d1274709d05d68a98de34168171d1

**Comment by yh-project** [comment]
mentioned in commit 94f0a127debb301052512a326661cf47d59433dc

**Comment by yh-project** [comment]
mentioned in commit bf7a0ebf25ca61b662997221d920f24f077cea59

**Comment by yh-project** [comment]
mentioned in commit 4161f95f96652d758f4db139e84136f27e4afcb9

**Comment by yh-project** [comment]
mentioned in commit d779a977bbf7e96c56ed5ff75ae561789105ed18

**Comment by yh-project** [comment]
mentioned in commit a2612dd5bba111f63218d3843a92c8bb82a881d6

**Comment by yh-project** [comment]
mentioned in commit 9ac0c9fde6eb4841ef129d9435badc6701b67976

**Comment by yh-project** [comment]
marked the checklist item **닉네임 validation 경고 메시지 추가** as completed

**Comment by yh-project** [comment]
marked the checklist item **닉네임 변경 타이틀 수정** as completed

**Comment by yh-project** [comment]
marked the checklist item **팀장한테만 팀 정보 수정 정보들 노출** as completed

**Comment by yh-project** [comment]
marked the checklist item **사람 검색은 이메일로 해야함을 표시** as completed

**Comment by yh-project** [comment]
marked the checklist item **carousel 프로젝트 로고 이미지 뷰 해결** as completed

**Comment by yh-project** [comment]
marked the checklist item **회원가입 step 에 따라 버튼이 안보이던 버그 해결** as completed

**Comment by yh-project** [comment]
marked the checklist item **프로젝트 로고 이미지 사진 혹은 .gif 만 가능하도록 경고** as completed

**Comment by yh-project** [comment]
mentioned in commit 7631cc30870db86e177e583e1a7d43ca3bf13db2

**Comment by yh-project** [comment]
mentioned in commit 588a9ed197c7ed0e2785688d6bd4af7d6b2022f6
