### ISSUE TITLE
[FE/Feat] Modal, BackDrop, PopUp 컴포넌트 구현

### ISSUE THREAD

**Issue by yh-project** [Shooot-PJT/shooot#5]
In GitLab by @altys31 on Oct 17, 2024, 16:49

## 📔 Description

공통 컴포넌트 중 하나인 BackDrop, Modal, PopUp을 구현하기 위함<br/>
피그마상의 디자인으로 구현하나, 컴포넌트 props 구성이나 구현 로직은 다를 수 있습니다.<br/>
![백드랍](https://my-gitlab-bucket.s3.amazonaws.com/891309600/dfe8b49852cc3964d5208b0c8fdbf1586819cbff59305f9badfdb9e03b9250e1/백드랍.PNG)<br/>
![모달](https://my-gitlab-bucket.s3.amazonaws.com/891309600/65d452c292f68e99bf22b7896251dd8d3fb48da9b29de7d1961deb2be9d7dd23/모달.PNG)<br/>
![팝업](https://my-gitlab-bucket.s3.amazonaws.com/891309600/254b16834df9b5aa07578263d7ef0036a8d816b3936806404563f6ff5ddcf2b1/팝업.PNG)<br/>

## 🐈 Todo

-   [x] BackDrop 컴포넌트 구현
-   [x] useModal Hook 구현
-   [x] usePopup Hook 구현

**Comment by yh-project** [comment]
In GitLab by @altys31 on Oct 17, 2024, 16:54

created branch [`feat/5-Modal`](/s11-final/S11P31D109/-/compare/develop...feat%2F5-Modal) to address this issue

**Comment by yh-project** [comment]
In GitLab by @altys31 on Oct 23, 2024, 22:00

marked the checklist item **BackDrop 컴포넌트 구현** as completed

**Comment by yh-project** [comment]
In GitLab by @altys31 on Oct 23, 2024, 22:00

marked the checklist item **useModal Hook 구현** as completed

**Comment by yh-project** [comment]
In GitLab by @altys31 on Oct 23, 2024, 22:00

marked the checklist item **usePopup Hook 구현** as completed

**Comment by yh-project** [comment]
In GitLab by @altys31 on Oct 24, 2024, 09:05

mentioned in commit d24a84e072ebc95455fea7829e25b05882a7a43e
