### ISSUE TITLE
[BE/Feat] 부하 테스트 실행기 기능 추가

### ISSUE THREAD

**Issue by yh-project** [Shooot-PJT/shooot#58]
In GitLab by @khj745700 on Nov 10, 2024, 19:46

## 📔 Description

부하 테스트 실행기 기능 추가 목적

## 🐈 Todo

- [x] SSE 연결 (프로젝트 용)
- [x] 배포된 서버 콘솔 로그 조회 기능 추가 ( Redis Streams Cold Stream을 사용해야 함 )
- [x] Docker Compose validation 기능 추가
- [x] Docker Compose 수정 기능 추가
- [x] Jar 파일 삭제
- [x] 서버 배포하기
- [x] 서버 배포 중지하기

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 10, 2024, 19:46

created branch [`feat/58-stress-feature`](/s11-final/S11P31D109/-/compare/develop...feat%2F58-stress-feature) to address this issue

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 11, 2024, 02:54

mentioned in commit 81d0fe9d0ec7b9e607074d57ce930857c535ba89

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 11, 2024, 17:17

mentioned in commit 31c86c70aba4ac90f28d404c90934d7d6d204476

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 11, 2024, 17:18

mentioned in commit 2e8462ccd20dfc1a412d4a801b3aff1f42efa70f

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 11, 2024, 17:20

mentioned in commit e21eaa3f5fe718afb091dd0cf203037660cd5001

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 11, 2024, 17:28

marked the checklist item **SSE 연결 (프로젝트 용)** as completed

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 11, 2024, 17:28

marked the checklist item **배포된 서버 콘솔 로그 조회 기능 추가 ( Redis Streams Cold Stream을 사용해야 함 )** as completed

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 11, 2024, 22:29

mentioned in commit 7788bd1f6a9f7414c31f9fa43985e9b9b6bc5cf3

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 12, 2024, 01:32

mentioned in commit 8e8ad09eb63f1008a2e4bc70fe6841ce6e55f63c

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 12, 2024, 01:34

mentioned in commit 0a86f395c6419f3598a8e599e7907df10c269596

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 12, 2024, 02:58

mentioned in commit 2761a5b8475fe13900546f982b1d50bcac8a0ee1

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 12, 2024, 03:01

mentioned in commit 67607983340918b9347d31f26196fdfaabde9a33

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 12, 2024, 03:10

mentioned in commit 3d49cc51c6d5fcb92afd266affbe16b04236102d

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 12, 2024, 03:15

mentioned in commit 25647e6c5dfab10bb33fb1b7dec12d36cb85a70f

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 12, 2024, 03:27

mentioned in commit 02ae5d552991765830097c8fa4a9d6893887be13

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 12, 2024, 09:31

mentioned in commit 6664d4c1e8db15bafcffb36bf2b96198b40e7dd4

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 12, 2024, 09:35

marked the checklist item **Docker Compose validation 기능 추가** as completed

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 12, 2024, 09:35

marked the checklist item **Docker Compose 수정 기능 추가** as completed

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 12, 2024, 09:35

marked the checklist item **Jar 파일 삭제** as completed

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 12, 2024, 09:35

marked the checklist item **서버 배포하기** as completed

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 12, 2024, 09:35

marked the checklist item **서버 배포 중지하기** as completed

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 12, 2024, 09:38

mentioned in commit ea29b5402bd6e9fcf6d7283b095046754def7263

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 12, 2024, 12:38

mentioned in commit 7e7c147c4124b82edb07b5906830c83b2b4f9810

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 12, 2024, 14:32

mentioned in commit 91e50eb1f5e5d7ac50a9c10b50f4060644345d08

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 12, 2024, 17:21

mentioned in commit 1aa1dffe44a251294b3c45a438186f33936c9e9a

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 12, 2024, 17:40

mentioned in commit 2800304d256ed6d5aef6109e93f434d01ba4c737

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 13, 2024, 09:20

mentioned in commit b7cdbcb1f717d410971c921aac2f7b07f26056a8

**Comment by yh-project** [comment]
In GitLab by @khj745700 on Nov 13, 2024, 11:00

mentioned in commit d14004f802342bbe414acaec3986fdb46cdbeb33
