### ISSUE TITLE
[FE/Fix] 사용자, 프로젝트 도메인 버그 수정, 예외 처리

### ISSUE THREAD

**Issue by yh-project** [Shooot-PJT/shooot#69]
## 📔 Description

사용자, 프로젝트 도메인 버그 수정, 예외 처리

## 🐈 Todo

- [x] 프로젝트 생성/수정 시 이미지 외의 파일 등록 예외 처리("image/*")
- [x] 일렉트론 윈도우 기본 zoom 설정(75%)
- [x] 엔터키로도 로그인 가능
- [x] NavBar 로고 클릭 이벤트 추가(내 프로젝트 메뉴로 이동)
- [x] NavBar menu, project 새로고침해도 고정(sessionStorage 이용) -> 브라우저 혹은 탭을 나가면 저장 해둘 필요 없다고 판단
- [x] 프로젝트 생성 후에 NavBar 의 carousel 생성 프로젝트로 안바뀌던 문제 해결
- [x] 초대 메일 전송 후에 modal 까지 꺼지도록 처리
- [x] 팀원이 혼자일 때에는 추방할 팀원이 없다는 popup 을 띄워주는 방식으로 수정
- [x] 팀원 초대에서 사람 검색 시 이메일 형식 검증을 통과한 후에만 검색 쿼리를 보내도록 수정
- [x] Banner 의 ProjectContent 에서 팀원 목록을 로딩 후에만 보이도록 수정

**Comment by yh-project** [comment]
created branch [`fix/69-user-project`](/s11-final/S11P31D109/-/compare/develop...fix%2F69-user-project) to address this issue

**Comment by yh-project** [comment]
mentioned in commit 454ce98b069ccb4c488b128675acff010ec593bb

**Comment by yh-project** [comment]
mentioned in commit f28a74123b009bd8a2c682781075b88aa7ed8f21

**Comment by yh-project** [comment]
mentioned in commit 2c24dd4569c680ccb69a9cd04df272453ef77cf2

**Comment by yh-project** [comment]
mentioned in commit de2d97501965dd1b61562e1080ff25fa19a86820

**Comment by yh-project** [comment]
mentioned in commit 1ed8c113371b9c6fe9a718087412aed928bf9af3

**Comment by yh-project** [comment]
mentioned in commit 1e68069588591853ed6985b9da6e36e4822da4ff

**Comment by yh-project** [comment]
mentioned in commit 391d17a8e27cf0f5c22f47a4e8df9a70cc24d38a

**Comment by yh-project** [comment]
mentioned in commit bc313cd623e17ecfd91092ac7a3ca5448149c853

**Comment by yh-project** [comment]
mentioned in commit fdcace688ba79619526260d280a10d2c835070a7

**Comment by yh-project** [comment]
mentioned in commit b8a43bd2bb9c8a504938a5f585fa39e993971f37

**Comment by yh-project** [comment]
mentioned in commit 0be4a1b8968566482bd8ce19e101434629bdc42a

**Comment by yh-project** [comment]
mentioned in commit 25f820ca5b0c57c5276db934379988d056c075b7

**Comment by yh-project** [comment]
mentioned in commit 7527e298ee46f16549d483903733efe64a1ad9e3
