### ISSUE TITLE
[FE/Feat] 회원 정보 관련 UI 추가

### ISSUE THREAD

**Issue by yh-project** [Shooot-PJT/shooot#78]
## 📔 Description

회원마다 가지는 프로필 색상 데이터가 고정됨에 따라 회원의 프로필을 보이는 곳에서 색상 UI 적용 추가

## 🐈 Todo

- [x] 팀원 조회 시 프로필 색상
- [x] 팀원 추방 시 프로필 색상
- [x] 회원 검색 시 프로필 색상

**Comment by yh-project** [comment]
created branch [`feat/78-profile-color`](/s11-final/S11P31D109/-/compare/develop...feat%2F78-profile-color) to address this issue

**Comment by yh-project** [comment]
marked the checklist item **팀원 조회 시 프로필 색상** as completed

**Comment by yh-project** [comment]
marked the checklist item **팀원 추방 시 프로필 색상** as completed

**Comment by yh-project** [comment]
marked the checklist item **회원 검색 시 프로필 색상** as completed

**Comment by yh-project** [comment]
mentioned in commit 240446ac18ca43394cff2a7f33062362d0dafbb6

**Comment by yh-project** [comment]
mentioned in commit 2c142547ab7c71b567a1c6b5ab9bb8277d023332

**Comment by yh-project** [comment]
mentioned in commit f263597958ffed679441dd767e6745abc2e4fc0e

**Comment by yh-project** [comment]
mentioned in commit d77e1f42b60741f337479379002e466712e5583b
