### ISSUE TITLE
[Mock/Feat] 시연용 뷰 개발

### ISSUE THREAD

**Issue by yh-project** [Shooot-PJT/shooot#93]
## 📔 Description

시연용 뷰 개발

## 🐈 Todo

- [x] 로그인을 위한 기본적인 폼
- [x] mswjs 를 활용한 mocking 구현
- [x] shooot 을 활용한 mocking 구현

**Comment by yh-project** [comment]
created branch [`feat/93-demo`](/s11-final/S11P31D109/-/compare/develop...feat%2F93-demo) to address this issue

**Comment by yh-project** [comment]
mentioned in commit 7c35dce7a731a3853b457ad774e9a02d062f6adc

**Comment by yh-project** [comment]
mentioned in commit b2e020b62c7ca8b7864fa590bd8a99a94ab81a64

**Comment by yh-project** [comment]
mentioned in commit 6825016eb0ae792f589050ea55adc9ff60011f38

**Comment by yh-project** [comment]
marked the checklist item **로그인을 위한 기본적인 폼** as completed

**Comment by yh-project** [comment]
marked the checklist item **mswjs 를 활용한 mocking 구현** as completed

**Comment by yh-project** [comment]
marked the checklist item **shooot 을 활용한 mocking 구현** as completed
