### ISSUE TITLE
[FE/Fix] 파악중인 버그 수정

### ISSUE THREAD

**Issue by yh-project** [Shooot-PJT/shooot#99]
In GitLab by @altys31 on Nov 18, 2024, 21:15

## 📔 Description

파악중인 버그들을 수정할 예정
## 🐈 Todo

-   [x] 그래프와 테이블의 반올림 로직에 의해 다르게 표기되는 데이터 수정
-   [x] SelectBox의 각 Item UI 깨지던 문제 수정
-   [x] 그래프의 항목과 다른 Title 수정
-   [x] 서버 테스트상의 오류로 생성된 잘못된 테스트 기록에 접근하지 못하도록 버튼 비활성화

**Comment by yh-project** [comment]
In GitLab by @altys31 on Nov 18, 2024, 21:16

created branch [`fix/99-bugs-fix`](/s11-final/S11P31D109/-/compare/develop...fix%2F99-bugs-fix) to address this issue

**Comment by yh-project** [comment]
In GitLab by @altys31 on Nov 18, 2024, 22:27

marked the checklist item **그래프와 테이블의 반올림 로직에 의해 다르게 표기되는 데이터 수정** as completed

**Comment by yh-project** [comment]
In GitLab by @altys31 on Nov 18, 2024, 22:28

marked the checklist item **그래프와 테이블의 반올림 로직에 의해 다르게 표기되는 데이터 수정** as incomplete

**Comment by yh-project** [comment]
In GitLab by @altys31 on Nov 18, 2024, 22:29

marked the checklist item **그래프와 테이블의 반올림 로직에 의해 다르게 표기되는 데이터 수정** as completed

**Comment by yh-project** [comment]
In GitLab by @altys31 on Nov 18, 2024, 22:49

marked the checklist item **SelectBox의 각 Item UI 깨지던 문제 수정** as completed

**Comment by yh-project** [comment]
In GitLab by @altys31 on Nov 19, 2024, 02:06

marked the checklist item **그래프의 항목과 다른 Title 수정** as completed

**Comment by yh-project** [comment]
In GitLab by @altys31 on Nov 19, 2024, 02:11

marked the checklist item **서버 테스트상의 오류로 생성된 잘못된 테스트 기록에 접근하지 못하도록 버튼 비활성화** as completed

**Comment by yh-project** [comment]
In GitLab by @altys31 on Nov 19, 2024, 02:55

created branch [`99-fe-fix`](/s11-final/S11P31D109/-/compare/develop...99-fe-fix) to address this issue

**Comment by yh-project** [comment]
In GitLab by @altys31 on Nov 19, 2024, 04:08

mentioned in commit e8acdc1ec937d4e482941668d012140daa637be0
